export const translations = {
    'en': {
        openNativeKey: 'Open Key', importKey: 'Import Key', clearFeatures: 'Clear Features', preferences: 'Preferences', assistant: 'Spot',
        loadKeyPrompt: 'Load a Lucid key to start.', processing: 'Processing...', error: 'Error', canceled: 'Canceled',
        toggleMenu: 'Toggle Menu', features: 'Features', entitiesRemaining: 'Entities Remaining',
        featuresChosen: 'Features Chosen', entitiesDiscarded: 'Entities Discarded', search: 'Search...',
        listView: 'List View', gridView: 'Grid View', clearHistory: 'Clear History', closePanel: 'Close Panel',
        folder: 'Folder',
        noImageAvailable: 'No image available', keyInfo: 'Key Information', language: 'Language',
        uiTheme: 'UI Theme', themeLight: 'Light', themeDark: 'Dark',
        uiShowToasts: 'Show Notifications',
        confirmClear: 'Are you sure you want to clear all chosen features?', featuresCleared: 'All features cleared.',
        aiReady: 'Describe an entity to identify it, or ask a question about this key.',
        aiWaiting: 'Waiting...', aiDescribe: 'Ask Spot...', aiNeedApi: 'Add your API key in preferences.',
        aiNeedKey: 'Load a key first.', aiAnalyzing: 'Analyzing...',
        aiNoFeatures: "I couldn't identify any specific features from your description. Could you please provide more details?",
        aiSingleMatch: 'Based on your description, the only possible match is',
        aiMultipleMatches: 'Based on your description, there are **{count}** possible matches:',
        aiNoMatch: 'I found features in your description, but no entities match all of them.',
        aiError: 'Sorry, an error occurred', otherFeature: 'Other', value: 'Value',
        scoreCommon: 'Common', scoreRare: 'Rare', scoreUncertain: 'Uncertain', scoreInterval: 'Interval',
        enterApiKey: 'Enter your API Key...',
        apiKeyNote: 'Your API key is stored only in your browser and is required for the AI assistant.',
        scoreCommonMisinterpret: 'Common (misinterpreted)',
        scoreRareMisinterpret: 'Rare (misinterpreted)',
        charParentOther: 'Others',
        hierarchy: 'Hierarchy',
        back: 'Back',
        aiFeaturesConsidered: 'Features Considered:',
        aiEntitiesConsidered: 'Entities Considered:',
        aiConsideredData: 'Considered Data',
        aiDisclaimer: 'AI answers might contain incorrect information. Please verify important details.',
        featureUpdated: 'Feature updated.',
        entitiesDiscardedCount: '{count} entities discarded. {remain} remaining.',
        entitiesRestoredCount: '{count} entities restored. {remain} remaining.',
        confirmClearHistory: 'Are you sure you want to clear the chat history?',
        copy: 'Copy',
        copied: 'Copied!',
        readMore: 'Read more',
        readLess: 'Read less',
        regenerate: 'Regenerate',
        edit: 'Edit',
        cancel: 'Cancel',
        save: 'Save',
        expandAll: 'Expand All',
        collapseAll: 'Collapse All',
        clearSearch: 'Clear Search', prevMatch: 'Previous Match', nextMatch: 'Next Match', loading: 'Loading...', 
        dropImageHere: 'Drop image here', previousVersion: 'Previous version', nextVersion: 'Next version', 
        resizePanel: 'Resize panel', ent: 'Ent', feat: 'Feat', fullScaleView: 'Full scale view', 
        uploadedImage: 'Uploaded image', preview: 'Preview', uploadImage: 'Upload Image',
        errCorruptedFile: 'The selected file could not be read. It might be corrupted or not a valid Lucid key (zip, lk4, lk5) file.', errDataDirNotFound: 'Invalid Lucid key zip: "Data" directory not found.', errKeyDataNotFound: 'Could not find or read "key.data" from the nested archive.', errProcessingKey: 'Failed to process key file.',
        prefsGeneral: 'General', prefsAI: 'AI Configuration',
    },
    'pt-br': {
        openNativeKey: 'Abrir Chave', importKey: 'Importar Chave', clearFeatures: 'Limpar Características', preferences: 'Preferências', assistant: 'Spot',
        loadKeyPrompt: 'Carregue uma chave Lucid para começar.', processing: 'Processando...', error: 'Erro', canceled: 'Cancelado.',
        toggleMenu: 'Abrir menu', features: 'Características', entitiesRemaining: 'Entidades Restantes',
        featuresChosen: 'Características Escolhidas', entitiesDiscarded: 'Entidades Descartadas', search: 'Buscar...',
        listView: 'Lista', gridView: 'Grade', clearHistory: 'Apagar histórico', closePanel: 'Fechar painel',
        folder: 'Pasta',
        noImageAvailable: 'Nenhuma imagem disponível', keyInfo: 'Informações da Chave', language: 'Idioma',
        uiTheme: 'Tema da Interface', themeLight: 'Claro', themeDark: 'Escuro',
        uiShowToasts: 'Mostrar Notificações',
        confirmClear: 'Tem certeza que deseja limpar todas as características escolhidas?', featuresCleared: 'Todas as características limpas.',
        aiReady: 'Descreva uma entidade para identificá-la ou faça uma pergunta sobre esta chave.',
        aiWaiting: 'Aguardando...', aiDescribe: 'Pergunte ao Spot...', aiNeedApi: 'Adicione a chave da API nas preferências.',
        aiNeedKey: 'Carregue uma chave primeiro.', aiAnalyzing: 'Analisando...',
        aiNoFeatures: "Não consegui identificar nenhuma característica específica da sua descrição. Você poderia fornecer mais detalhes?",
        aiSingleMatch: 'Com base na sua descrição, o único resultado possível é',
        aiMultipleMatches: 'Com base na sua descrição, existem **{count}** resultados possíveis:',
        aiNoMatch: 'Encontrei características na sua descrição, mas nenhuma entidade corresponde a todas elas.',
        aiError: 'Desculpe, ocorreu um erro', otherFeature: 'Outra', value: 'Valor',
        scoreCommon: 'Comum', scoreRare: 'Raro', scoreUncertain: 'Incerto', scoreInterval: 'Intervalo',
        enterApiKey: 'Digite sua chave de API...',
        apiKeyNote: 'Sua chave de API é armazenada apenas no seu navegador e é necessária para o assistente de IA.',
        scoreCommonMisinterpret: 'Comum (mal interpretado)',
        scoreRareMisinterpret: 'Raro (mal interpretado)',
        charParentOther: 'Outras',
        hierarchy: 'Hierarquia',
        back: 'Voltar',
        aiFeaturesConsidered: 'Características Consideradas:',
        aiEntitiesConsidered: 'Entidades Consideradas:',
        aiConsideredData: 'Dados Considerados',
        aiDisclaimer: 'As respostas da IA podem conter informações incorretas. Por favor, verifique os detalhes importantes.',
        featureUpdated: 'Característica atualizada.',
        entitiesDiscardedCount: '{count} entidades descartadas. {remain} restantes.',
        entitiesRestoredCount: '{count} entidades restauradas. {remain} restantes.',
        confirmClearHistory: 'Tem certeza de que deseja limpar o histórico do chat?',
        copy: 'Copiar',
        copied: 'Copiado!',
        readMore: 'Ler mais',
        readLess: 'Ler menos',
        regenerate: 'Regenerar',
        edit: 'Editar',
        cancel: 'Cancelar',
        save: 'Salvar',
        expandAll: 'Expandir Tudo',
        collapseAll: 'Recolher Tudo',
        clearSearch: 'Limpar Busca', prevMatch: 'Resultado Anterior', nextMatch: 'Próximo Resultado', loading: 'Carregando...', 
        dropImageHere: 'Solte a imagem aqui', previousVersion: 'Versão anterior', nextVersion: 'Próxima versão', 
        resizePanel: 'Redimensionar painel', ent: 'Ent', feat: 'Carac', fullScaleView: 'Visualização em tamanho real', 
        uploadedImage: 'Imagem enviada', preview: 'Visualização', uploadImage: 'Enviar Imagem',
        errCorruptedFile: 'O arquivo selecionado não pôde ser lido. Ele pode estar corrompido ou não ser um arquivo de chave Lucid válido (zip, lk4, lk5).', errDataDirNotFound: 'Zip de chave Lucid inválido: diretório "Data" não encontrado.', errKeyDataNotFound: 'Não foi possível encontrar ou ler "key.data" do arquivo aninhado.', errProcessingKey: 'Falha ao processar o arquivo da chave.',
        prefsGeneral: 'Geral', prefsAI: 'Configuração de IA',
    },
    'es': {
        openNativeKey: 'Abrir Clave', importKey: 'Importar Clave', clearFeatures: 'Borrar Características', preferences: 'Preferencias', assistant: 'Spot',
        loadKeyPrompt: 'Carga una clave Lucid para comenzar.', processing: 'Procesando...', error: 'Error', canceled: 'Cancelado.',
        toggleMenu: 'Alternar menú', features: 'Características', entitiesRemaining: 'Entidades Restantes',
        featuresChosen: 'Características Elegidas', entitiesDiscarded: 'Entidades Descartadas', search: 'Buscar...',
        listView: 'Vista de lista', gridView: 'Vista de cuadrícula', clearHistory: 'Limpiar historial', closePanel: 'Cerrar panel',
        folder: 'Carpeta',
        noImageAvailable: 'No hay imagen disponible', keyInfo: 'Información de la Clave', language: 'Idioma',
        uiTheme: 'Tema de la Interfaz', themeLight: 'Claro', themeDark: 'Oscuro',
        uiShowToasts: 'Mostrar Notificaciones',
        confirmClear: '¿Estás seguro de que quieres borrar todas las características elegidas?', featuresCleared: 'Todas las características borradas.',
        aiReady: 'Describe una entidad para identificarla, o haz una pregunta sobre esta clave.',
        aiWaiting: 'Esperando...', aiDescribe: 'Pregúntale a Spot...', aiNeedApi: 'Añade tu clave de API en las preferencias.',
        aiNeedKey: 'Primero carga una clave.', aiAnalyzing: 'Analizando...',
        aiNoFeatures: "No pude identificar ninguna característica específica de tu descripción. ¿Podrías dar más detalles?",
        aiSingleMatch: 'Según tu descripción, la única coincidencia posible es',
        aiMultipleMatches: 'Según tu descripción, hay **{count}** posibles coincidencias:',
        aiNoMatch: 'Encontré características en tu descripción, pero ninguna entidad coincide con todas ellas.',
        aiError: 'Lo siento, ocurrió un error', otherFeature: 'Otro', value: 'Valor',
        scoreCommon: 'Común', scoreRare: 'Raro', scoreUncertain: 'Incierto', scoreInterval: 'Intervalo',
        enterApiKey: 'Introduce tu clave de API...',
        apiKeyNote: 'Tu clave de API se almacena solo en tu navegador y es necesaria para el asistente de IA.',
        scoreCommonMisinterpret: 'Común (mal interpretado)',
        scoreRareMisinterpret: 'Raro (mal interpretado)',
        charParentOther: 'Otros',
        hierarchy: 'Jerarquía',
        back: 'Atrás',
        aiFeaturesConsidered: 'Características Consideradas:',
        aiEntitiesConsidered: 'Entidades Consideradas:',
        aiConsideredData: 'Datos Considerados',
        aiDisclaimer: 'Las respuestas de la IA pueden contener información incorrecta. Por favor, verifica los detalles importantes.',
        featureUpdated: 'Característica actualizada.',
        entitiesDiscardedCount: '{count} entidades descartadas. {remain} restantes.',
        entitiesRestoredCount: '{count} entidades restauradas. {remain} restantes.',
        confirmClearHistory: '¿Estás seguro de que quieres borrar el historial del chat?',
        copy: 'Copiar',
        copied: '¡Copiado!',
        readMore: 'Leer más',
        readLess: 'Leer menos',
        regenerate: 'Regenerar',
        edit: 'Editar',
        cancel: 'Cancelar',
        save: 'Guardar',
        expandAll: 'Expandir Todo',
        collapseAll: 'Colapsar Todo',
        clearSearch: 'Limpiar Búsqueda', prevMatch: 'Coincidencia Anterior', nextMatch: 'Siguiente Coincidencia', loading: 'Cargando...', 
        dropImageHere: 'Suelta la imagen aquí', previousVersion: 'Versión anterior', nextVersion: 'Siguiente versión', 
        resizePanel: 'Cambiar tamaño del panel', ent: 'Ent', feat: 'Carac', fullScaleView: 'Vista a escala completa', 
        uploadedImage: 'Imagen subida', preview: 'Vista previa', uploadImage: 'Subir Imagen',
        errCorruptedFile: 'El archivo seleccionado no se pudo leer. Podría estar dañado o no ser un archivo de clave Lucid válido (zip, lk4, lk5).', errDataDirNotFound: 'Zip de clave Lucid no válido: no se encontró el directorio "Data".', errKeyDataNotFound: 'No se pudo encontrar o leer "key.data" desde el archivo anidado.', errProcessingKey: 'Error al procesar el archivo de la clave.',
        prefsGeneral: 'General', prefsAI: 'Configuración de IA',
    },
    'ru': {
        openNativeKey: 'Открыть ключ', importKey: 'Импортировать ключ', clearFeatures: 'Очистить признаки', preferences: 'Настройки', assistant: 'Барбос',
        loadKeyPrompt: 'Загрузите ключ Lucid, чтобы начать.', processing: 'Обработка...', error: 'Ошибка', canceled: 'Отменено',
        toggleMenu: 'Переключить меню', features: 'Признаки', entitiesRemaining: 'Оставшиеся сущности',
        featuresChosen: 'Выбранные признаки', entitiesDiscarded: 'Отброшенные сущности', search: 'Поиск...',
        listView: 'Вид списком', gridView: 'Вид сеткой', clearHistory: 'Очистить историю', closePanel: 'Закрыть панель',
        folder: 'Папка',
        noImageAvailable: 'Изображение недоступно', keyInfo: 'Информация о ключе', language: 'Язык',
        uiTheme: 'Тема интерфейса', themeLight: 'Светлая', themeDark: 'Темная',
        uiShowToasts: 'Показывать уведомления',
        confirmClear: 'Вы уверены, что хотите очистить все выбранные признаки?', featuresCleared: 'Все признаки очищены.',
        aiReady: 'Опишите сущность для ее идентификации или задайте вопрос об этом ключе.',
        aiWaiting: 'Ожидание...', aiDescribe: 'Спросите Spot...', aiNeedApi: 'Добавьте ваш API-ключ в настройках.',
        aiNeedKey: 'Сначала загрузите ключ.', aiAnalyzing: 'Анализ...',
        aiNoFeatures: 'Я не смог определить какие-либо конкретные признаки из вашего описания. Не могли бы вы предоставить больше деталей?',
        aiSingleMatch: 'На основе вашего описания единственное возможное совпадение - это',
        aiMultipleMatches: 'На основе вашего описания есть **{count}** возможных совпадений:',
        aiNoMatch: 'Я нашел признаки в вашем описании, но ни одна сущность не соответствует всем им.',
        aiError: 'Извините, произошла ошибка', otherFeature: 'Другое', value: 'Значение',
        scoreCommon: 'Обычный', scoreRare: 'Редкий', scoreUncertain: 'Неопределенный', scoreInterval: 'Интервал',
        enterApiKey: 'Введите ваш API-ключ...',
        apiKeyNote: 'Ваш API-ключ хранится только в вашем браузере и необходим для работы AI-помощника.',
        scoreCommonMisinterpret: 'Обычный (неверно истолкован)',
        scoreRareMisinterpret: 'Редкий (неверно истолкован)',
        charParentOther: 'Другие',
        hierarchy: 'Иерархия',
        back: 'Назад',
        aiFeaturesConsidered: 'Учтенные признаки:',
        aiEntitiesConsidered: 'Учтенные сущности:',
        aiConsideredData: 'Учтенные данные',
        aiDisclaimer: 'Ответы ИИ могут содержать неверную информацию. Пожалуйста, проверяйте важные детали.',
        featureUpdated: 'Признак обновлен.',
        entitiesDiscardedCount: '{count} сущностей отброшено. {remain} осталось.',
        entitiesRestoredCount: '{count} сущностей восстановлено. {remain} осталось.',
        confirmClearHistory: 'Вы уверены, что хотите очистить историю чата?',
        copy: 'Копировать',
        copied: 'Скопировано!',
        readMore: 'Читать далее',
        readLess: 'Свернуть',
        regenerate: 'Сгенерировать заново',
        edit: 'Изменить',
        cancel: 'Отмена',
        save: 'Сохранить',
        expandAll: 'Развернуть все',
        collapseAll: 'Свернуть все',
        clearSearch: 'Очистить поиск', prevMatch: 'Предыдущее совпадение', nextMatch: 'Следующее совпадение', loading: 'Загрузка...', 
        dropImageHere: 'Перетащите изображение сюда', previousVersion: 'Предыдущая версия', nextVersion: 'Следующая версия', 
        resizePanel: 'Изменить размер панели', ent: 'Сущ', feat: 'Призн', fullScaleView: 'Полномасштабный просмотр', 
        uploadedImage: 'Загруженное изображение', preview: 'Предпросмотр', uploadImage: 'Загрузить изображение',
        errCorruptedFile: 'Не удалось прочитать выбранный файл. Возможно, он поврежден или не является допустимым файлом ключа Lucid (zip, lk4, lk5).', errDataDirNotFound: 'Недопустимый zip-архив ключа Lucid: каталог "Data" не найден.', errKeyDataNotFound: 'Не удалось найти или прочитать "key.data" из вложенного архива.', errProcessingKey: 'Не удалось обработать файл ключа.',
        prefsGeneral: 'Общие', prefsAI: 'Настройки ИИ',
    },
    'zh': {
        openNativeKey: '打开密钥', importKey: '导入密钥', clearFeatures: '清除特征', preferences: '偏好设置', assistant: 'Spot',
        loadKeyPrompt: '加载Lucid密钥以开始。', processing: '处理中...', error: '错误', canceled: '已取消',
        toggleMenu: '切换菜单', features: '特征', entitiesRemaining: '剩余实体',
        featuresChosen: '已选特征', entitiesDiscarded: '已弃实体', search: '搜索...',
        listView: '列表视图', gridView: '网格视图', clearHistory: '清除历史记录', closePanel: '关闭面板',
        folder: '文件夹',
        noImageAvailable: '无可用图像', keyInfo: '密钥信息', language: '语言',
        uiTheme: '界面主题', themeLight: '浅色', themeDark: '深色',
        uiShowToasts: '显示通知',
        confirmClear: '您确定要清除所有已选特征吗？', featuresCleared: '所有特征已清除。',
        aiReady: '描述一个实体以识别它，或询问有关此密钥的问题。',
        aiWaiting: '等待中...', aiDescribe: '询问 Spot...', aiNeedApi: '请在偏好设置中添加您的API密钥。',
        aiNeedKey: '请先加载一个密钥。', aiAnalyzing: '分析中...',
        aiNoFeatures: '我无法从您的描述中识别出任何具体特征。您能提供更多细节吗？',
        aiSingleMatch: '根据您的描述，唯一可能的匹配是',
        aiMultipleMatches: '根据您的描述，有**{count}**个可能的匹配项：',
        aiNoMatch: '我在您的描述中找到了特征，但没有实体能匹配所有这些特征。',
        aiError: '抱歉，发生了错误', otherFeature: '其他', value: '值',
        scoreCommon: '常见', scoreRare: '罕见', scoreUncertain: '不确定', scoreInterval: '区间',
        enterApiKey: '输入您的API密钥...',
        apiKeyNote: '您的API密钥仅存储在您的浏览器中，AI助手需要使用它。',
        scoreCommonMisinterpret: '常见（误解）',
        scoreRareMisinterpret: '罕见（误解）',
        charParentOther: '其他',
        hierarchy: '层级结构',
        back: '返回',
        aiFeaturesConsidered: '考虑的特征：',
        aiEntitiesConsidered: '考虑的实体：',
        aiConsideredData: '考虑的数据',
        aiDisclaimer: 'AI的回答可能包含不准确的信息。请核实重要细节。',
        featureUpdated: '特征已更新。',
        entitiesDiscardedCount: '已弃 {count} 个实体。剩余 {remain} 个。',
        entitiesRestoredCount: '已恢复 {count} 个实体。剩余 {remain} 个。',
        confirmClearHistory: '您确定要清除聊天记录吗？',
        copy: '复制',
        copied: '已复制！',
        readMore: '阅读更多',
        readLess: '收起',
        regenerate: '重新生成',
        edit: '编辑',
        cancel: '取消',
        save: '保存',
        expandAll: '全部展开',
        collapseAll: '全部折叠',
        clearSearch: '清除搜索', prevMatch: '上一个匹配项', nextMatch: '下一个匹配项', loading: '加载中...', 
        dropImageHere: '将图像拖放到此处', previousVersion: '上一版本', nextVersion: '下一版本', 
        resizePanel: '调整面板大小', ent: '实体', feat: '特征', fullScaleView: '全尺寸视图', 
        uploadedImage: '上传的图像', preview: '预览', uploadImage: '上传图像',
        errCorruptedFile: '无法读取所选文件。它可能已损坏，或者不是有效的 Lucid 密钥文件 (zip, lk4, lk5)。', errDataDirNotFound: '无效的 Lucid 密钥 zip："Data" 目录未找到。', errKeyDataNotFound: '无法从嵌套存档中找到或读取 "key.data"。', errProcessingKey: '处理密钥文件失败。',
        prefsGeneral: '常规', prefsAI: 'AI配置',
    },
    'ja': {
        openNativeKey: 'キーを開く', importKey: 'キーをインポート', clearFeatures: '特徴をクリア', preferences: '設定', assistant: 'スポット',
        loadKeyPrompt: '開始するにはLucidキーを読み込んでください。', processing: '処理中...', error: 'エラー', canceled: 'キャンセルされました',
        toggleMenu: 'メニューを切り替え', features: '特徴', entitiesRemaining: '残りのエンティティ',
        featuresChosen: '選択された特徴', entitiesDiscarded: '破棄されたエンティティ', search: '検索...',
        listView: 'リスト表示', gridView: 'グリッド表示', clearHistory: '履歴をクリア', closePanel: 'パネルを閉じる',
        folder: 'フォルダー',
        noImageAvailable: '画像がありません', keyInfo: 'キー情報', language: '言語',
        uiTheme: 'UIテーマ', themeLight: 'ライト', themeDark: 'ダーク',
        uiShowToasts: '通知を表示',
        confirmClear: '選択したすべての特徴をクリアしてもよろしいですか？', featuresCleared: 'すべての特徴がクリアされました。',
        aiReady: 'エンティティを説明して識別するか、このキーについて質問してください。',
        aiWaiting: '待機中...', aiDescribe: 'Spotに質問する...', aiNeedApi: '設定でAPIキーを追加してください。',
        aiNeedKey: '最初にキーを読み込んでください。', aiAnalyzing: '分析中...',
        aiNoFeatures: 'あなたの説明から特定の特徴を識別できませんでした。詳細を教えていただけますか？',
        aiSingleMatch: 'あなたの説明に基づくと、唯一の一致可能性は',
        aiMultipleMatches: 'あなたの説明に基づくと、**{count}**件の一致可能性があります：',
        aiNoMatch: 'あなたの説明に特徴を見つけましたが、すべての特徴に一致するエンティティはありません。',
        aiError: '申し訳ありません、エラーが発生しました', otherFeature: 'その他', value: '値',
        scoreCommon: '一般的', scoreRare: 'まれ', scoreUncertain: '不確実', scoreInterval: '間隔',
        enterApiKey: 'APIキーを入力してください...',
        apiKeyNote: 'APIキーはブラウザにのみ保存され、AIアシスタントに必要です。',
        scoreCommonMisinterpret: '一般的（誤解）',
        scoreRareMisinterpret: 'まれ（誤解）',
        charParentOther: 'その他',
        hierarchy: '階層',
        back: '戻る',
        aiFeaturesConsidered: '考慮された特徴：',
        aiEntitiesConsidered: '考慮されたエンティティ：',
        aiConsideredData: '考慮されたデータ',
        aiDisclaimer: 'AIの回答には誤った情報が含まれる可能性があります。重要な詳細は確認してください。',
        featureUpdated: '特徴が更新されました。',
        entitiesDiscardedCount: '{count} 件のエンティティが破棄されました。残り {remain} 件。',
        entitiesRestoredCount: '{count} 件のエンティティが復元されました。残り {remain} 件。',
        confirmClearHistory: 'チャット履歴をクリアしてもよろしいですか？',
        copy: 'コピー',
        copied: 'コピーしました！',
        readMore: '続きを読む',
        readLess: '折りたたむ',
        regenerate: '再生成',
        edit: '編集',
        cancel: 'キャンセル',
        save: '保存',
        expandAll: 'すべて展開',
        collapseAll: 'すべて折りたたむ',
        clearSearch: '検索をクリア', prevMatch: '前の一致', nextMatch: '次の一致', loading: '読み込み中...', 
        dropImageHere: 'ここに画像をドロップ', previousVersion: '前のバージョン', nextVersion: '次のバージョン', 
        resizePanel: 'パネルのサイズ変更', ent: 'Ent', feat: 'Feat', fullScaleView: 'フルスケール表示', 
        uploadedImage: 'アップロードされた画像', preview: 'プレビュー', uploadImage: '画像をアップロード',
        errCorruptedFile: '選択したファイルを読み取れませんでした。破損しているか、有効なLucidキー（zip、lk4、lk5）ファイルではない可能性があります。', errDataDirNotFound: '無効なLucidキーのzip：「Data」ディレクトリが見つかりません。', errKeyDataNotFound: 'ネストされたアーカイブから「key.data」を見つけるか読み取ることができませんでした。', errProcessingKey: 'キーファイルの処理に失敗しました。',
        prefsGeneral: '一般', prefsAI: 'AI設定',
    },
    'fr': {
        openNativeKey: 'Ouvrir la Clé', importKey: 'Importer la Clé', clearFeatures: 'Effacer les caractéristiques', preferences: 'Préférences', assistant: 'Spot',
        loadKeyPrompt: 'Chargez une clé Lucid pour commencer.', processing: 'Traitement...', error: 'Erreur', canceled: 'Annulé',
        toggleMenu: 'Basculer le menu', features: 'Caractéristiques', entitiesRemaining: 'Entités Restantes',
        featuresChosen: 'Caractéristiques Choisies', entitiesDiscarded: 'Entités Rejetées', search: 'Rechercher...',
        listView: 'Vue liste', gridView: 'Vue grille', clearHistory: 'Effacer l\'historique', closePanel: 'Fermer le panneau',
        folder: 'Dossier',
        noImageAvailable: 'Aucune image disponible', keyInfo: 'Informations sur la Clé', language: 'Langue',
        uiTheme: 'Thème de l\'interface', themeLight: 'Clair', themeDark: 'Sombre',
        uiShowToasts: 'Afficher les notifications',
        confirmClear: 'Êtes-vous sûr de vouloir effacer toutes les caractéristiques choisies ?', featuresCleared: 'Toutes les caractéristiques ont été effacées.',
        aiReady: 'Décrivez une entité pour l\'identifier, ou posez une question sur cette clé.',
        aiWaiting: 'En attente...', aiDescribe: 'Demandez à Spot...', aiNeedApi: 'Ajoutez votre clé API dans les préférences.',
        aiNeedKey: 'Chargez d\'abord une clé.', aiAnalyzing: 'Analyse en cours...',
        aiNoFeatures: "Je n'ai pu identifier aucune caractéristique spécifique à partir de votre description. Pourriez-vous fournir plus de détails ?",
        aiSingleMatch: 'D\'après votre description, la seule correspondance possible est',
        aiMultipleMatches: 'D\'après votre description, il y a **{count}** correspondances possibles :',
        aiNoMatch: 'J\'ai trouvé des caractéristiques dans votre description, mais aucune entité ne correspond à toutes.',
        aiError: 'Désolé, une erreur est survenue', otherFeature: 'Autre', value: 'Valeur',
        scoreCommon: 'Commun', scoreRare: 'Rare', scoreUncertain: 'Incertain', scoreInterval: 'Intervalle',
        enterApiKey: 'Entrez votre clé API...',
        apiKeyNote: 'Votre clé API est stockée uniquement dans votre navigateur et est requise pour l\'assistant IA.',
        scoreCommonMisinterpret: 'Commun (mal interprété)',
        scoreRareMisinterpret: 'Rare (mal interprété)',
        charParentOther: 'Autres',
        hierarchy: 'Hiérarchie',
        back: 'Retour',
        aiFeaturesConsidered: 'Caractéristiques Considérées :',
        aiEntitiesConsidered: 'Entités Considérées :',
        aiConsideredData: 'Données Considérées',
        aiDisclaimer: 'Les réponses de l\'IA peuvent contenir des informations incorrectes. Veuillez vérifier les détails importants.',
        featureUpdated: 'Caractéristique mise à jour.',
        entitiesDiscardedCount: '{count} entités rejetées. {remain} restantes.',
        entitiesRestoredCount: '{count} entités restaurées. {remain} restantes.',
        confirmClearHistory: 'Êtes-vous sûr de vouloir effacer l\'historique du chat ?',
        copy: 'Copier',
        copied: 'Copié !',
        readMore: 'Lire la suite',
        readLess: 'Réduire',
        regenerate: 'Régénérer',
        edit: 'Modifier',
        cancel: 'Annuler',
        save: 'Enregistrer',
        expandAll: 'Tout développer',
        collapseAll: 'Tout réduire',
        clearSearch: 'Effacer la recherche', prevMatch: 'Correspondance précédente', nextMatch: 'Correspondance suivante', loading: 'Chargement...', 
        dropImageHere: 'Déposez l\'image ici', previousVersion: 'Version précédente', nextVersion: 'Version suivante', 
        resizePanel: 'Redimensionner le panneau', ent: 'Ent', feat: 'Carac', fullScaleView: 'Vue en taille réelle', 
        uploadedImage: 'Image téléchargée', preview: 'Aperçu', uploadImage: 'Télécharger une image',
        errCorruptedFile: 'Le fichier sélectionné n\'a pas pu être lu. Il est peut-être corrompu ou ne constitue pas un fichier de clé Lucid valide (zip, lk4, lk5).', errDataDirNotFound: 'Zip de clé Lucid invalide : répertoire "Data" introuvable.', errKeyDataNotFound: 'Impossible de trouver ou de lire "key.data" à partir de l\'archive imbriquée.', errProcessingKey: 'Échec du traitement du fichier de clé.',
        prefsGeneral: 'Général', prefsAI: 'Configuration IA',
    },
    'de': {
        openNativeKey: 'Schlüssel öffnen', importKey: 'Schlüssel importieren', clearFeatures: 'Merkmale löschen', preferences: 'Einstellungen', assistant: 'Spot',
        loadKeyPrompt: 'Laden Sie einen Lucid-Schlüssel, um zu beginnen.', processing: 'Verarbeite...', error: 'Fehler', canceled: 'Abgebrochen',
        toggleMenu: 'Menü umschalten', features: 'Merkmale', entitiesRemaining: 'Verbleibende Entitäten',
        featuresChosen: 'Gewählte Merkmale', entitiesDiscarded: 'Verworfene Entitäten', search: 'Suchen...',
        listView: 'Listenansicht', gridView: 'Gitteransicht', clearHistory: 'Verlauf löschen', closePanel: 'Panel schließen',
        folder: 'Ordner',
        noImageAvailable: 'Kein Bild verfügbar', keyInfo: 'Schlüsselinformationen', language: 'Sprache',
        uiTheme: 'UI-Thema', themeLight: 'Hell', themeDark: 'Dunkel',
        uiShowToasts: 'Benachrichtigungen anzeigen',
        confirmClear: 'Sind Sie sicher, dass Sie alle gewählten Merkmale löschen möchten?', featuresCleared: 'Alle Merkmale gelöscht.',
        aiReady: 'Beschreiben Sie eine Entität, um sie zu identifizieren, oder stellen Sie eine Frage zu diesem Schlüssel.',
        aiWaiting: 'Warte...', aiDescribe: 'Frag Spot...', aiNeedApi: 'Fügen Sie Ihren API-Schlüssel in den Einstellungen hinzu.',
        aiNeedKey: 'Laden Sie zuerst einen Schlüssel.', aiAnalyzing: 'Analysiere...',
        aiNoFeatures: 'Ich konnte aus Ihrer Beschreibung keine spezifischen Merkmale identifizieren. Könnten Sie bitte mehr Details angeben?',
        aiSingleMatch: 'Basierend auf Ihrer Beschreibung ist die einzig mögliche Übereinstimmung',
        aiMultipleMatches: 'Basierend auf Ihrer Beschreibung gibt es **{count}** mögliche Übereinstimmungen:',
        aiNoMatch: 'Ich habe Merkmale in Ihrer Beschreibung gefunden, aber keine Entitäten stimmen mit allen überein.',
        aiError: 'Entschuldigung, ein Fehler ist aufgetreten', otherFeature: 'Andere', value: 'Wert',
        scoreCommon: 'Häufig', scoreRare: 'Selten', scoreUncertain: 'Unsicher', scoreInterval: 'Intervall',
        enterApiKey: 'Geben Sie Ihren API-Schlüssel ein...',
        apiKeyNote: 'Ihr API-Schlüssel wird nur in Ihrem Browser gespeichert und wird für den KI-Assistenten benötigt.',
        scoreCommonMisinterpret: 'Häufig (falsch interpretiert)',
        scoreRareMisinterpret: 'Selten (falsch interpretiert)',
        charParentOther: 'Andere',
        hierarchy: 'Hierarchie',
        back: 'Zurück',
        aiFeaturesConsidered: 'Berücksichtigte Merkmale:',
        aiEntitiesConsidered: 'Berücksichtigte Entitäten:',
        aiConsideredData: 'Berücksichtigte Daten',
        aiDisclaimer: 'KI-Antworten können falsche Informationen enthalten. Bitte überprüfen Sie wichtige Details.',
        featureUpdated: 'Merkmal aktualisiert.',
        entitiesDiscardedCount: '{count} Entitäten verworfen. {remain} verbleibend.',
        entitiesRestoredCount: '{count} Entitäten wiederhergestellt. {remain} verbleibend.',
        confirmClearHistory: 'Möchten Sie den Chat-Verlauf wirklich löschen?',
        copy: 'Kopieren',
        copied: 'Kopiert!',
        readMore: 'Mehr lesen',
        readLess: 'Weniger lesen',
        regenerate: 'Neu generieren',
        edit: 'Bearbeiten',
        cancel: 'Abbrechen',
        save: 'Speichern',
        expandAll: 'Alle erweitern',
        collapseAll: 'Alle reduzieren',
        clearSearch: 'Suche löschen', prevMatch: 'Vorheriger Treffer', nextMatch: 'Nächster Treffer', loading: 'Laden...', 
        dropImageHere: 'Bild hier ablegen', previousVersion: 'Vorherige Version', nextVersion: 'Nächste Version', 
        resizePanel: 'Panelgröße ändern', ent: 'Ent', feat: 'Merk', fullScaleView: 'Vollbildansicht', 
        uploadedImage: 'Hochgeladenes Bild', preview: 'Vorschau', uploadImage: 'Bild hochladen',
        errCorruptedFile: 'Die ausgewählte Datei konnte nicht gelesen werden. Sie ist möglicherweise beschädigt oder keine gültige Lucid-Schlüsseldatei (zip, lk4, lk5).', errDataDirNotFound: 'Ungültiges Lucid-Schlüssel-Zip: Verzeichnis "Data" nicht gefunden.', errKeyDataNotFound: '"key.data" konnte im verschachtelten Archiv nicht gefunden oder gelesen werden.', errProcessingKey: 'Schlüsseldatei konnte nicht verarbeitet werden.',
        prefsGeneral: 'Allgemein', prefsAI: 'KI-Konfiguration',
    },
    'la': {
        openNativeKey: 'Aperi Clavem Nativam', importKey: 'Importare Clavem', clearFeatures: 'Proprietates Purgare', preferences: 'Praeferentiae', assistant: 'Spotus',
        loadKeyPrompt: 'Carica clavem Lucid ut incipias.', processing: 'Processus...', error: 'Error', canceled: 'Cancellatum',
        toggleMenu: 'Commuta Menu', features: 'Proprietates', entitiesRemaining: 'Entia Manentia',
        featuresChosen: 'Proprietates Electae', entitiesDiscarded: 'Entia Reiecta', search: 'Quaerere...',
        listView: 'Visus Listae', gridView: 'Visus Craticulae', clearHistory: 'Historia Purgare', closePanel: 'Claude Panel',
        folder: 'Fasciculus',
        noImageAvailable: 'Nulla Imago Praesto', keyInfo: 'Informatio Clavis', language: 'Lingua',
        uiTheme: 'Thema UI', themeLight: 'Lux', themeDark: 'Tenebrae',
        uiShowToasts: 'Ostende Notificationes',
        confirmClear: 'Certe vis omnes proprietates electae purgare?', featuresCleared: 'Omnes proprietates purgatae sunt.',
        aiReady: 'Describe ens ut id identifices, vel quaere de hac clave.',
        aiWaiting: 'Exspecto...', aiDescribe: 'Roga Spotum...', aiNeedApi: 'Adde clavem API tuam in praeferentiis.',
        aiNeedKey: 'Primum clavem carica.', aiAnalyzing: 'Analysans...',
        aiNoFeatures: 'Nullas notas specificas ex descriptione tua cognoscere potui. Potesne plura singula praebere?',
        aiSingleMatch: 'Ex descriptione tua, sola congruentia possibilis est',
        aiMultipleMatches: 'Ex descriptione tua, sunt **{count}** congruentiae possibiles:',
        aiNoMatch: 'Notas in descriptione tua inveni, sed nullum ens omnibus congruit.',
        aiError: 'Me paenitet, error accidit', otherFeature: 'Alia', value: 'Valor',
        scoreCommon: 'Communis', scoreRare: 'Rarus', scoreUncertain: 'Incertus', scoreInterval: 'Intervallum',
        enterApiKey: 'Clavem API tuam inscribe...',
        apiKeyNote: 'Clavis API tua in navigatro tuo tantum servatur et ad adiutorem AI requiritur.',
        scoreCommonMisinterpret: 'Communis (male interpretatus)', scoreRareMisinterpret: 'Rarus (male interpretatus)',
        hierarchy: 'Hierarchia',
        charParentOther: 'Alii',
        back: 'Redire',
        aiFeaturesConsidered: 'Proprietates Consideratae:',
        aiEntitiesConsidered: 'Entia Considerata:',
        aiConsideredData: 'Data Considerata',
        aiDisclaimer: 'Responsa AI possunt continere informationes falsas. Quaeso verifica singula magna.',
        featureUpdated: 'Proprietas renovata.',
        entitiesDiscardedCount: '{count} entia reiecta. {remain} manentia.',
        entitiesRestoredCount: '{count} entia restituta. {remain} manentia.',
        confirmClearHistory: 'Certe vis historiam colloquii purgare?',
        copy: 'Exemplar',
        copied: 'Exemplatum!',
        readMore: 'Plura legere',
        readLess: 'Pauciora legere',
        regenerate: 'Regenerare',
        edit: 'Emendare',
        cancel: 'Abolere',
        save: 'Servare',
        expandAll: 'Omnia Dilatare',
        collapseAll: 'Omnia Contrahere',
        clearSearch: 'Purgare inquisitionem', prevMatch: 'Praecedens congruentia', nextMatch: 'Proxima congruentia', loading: 'Caricans...', 
        dropImageHere: 'Pone imaginem hic', previousVersion: 'Versio prior', nextVersion: 'Proxima versio', 
        resizePanel: 'Mutare magnitudinem panel', ent: 'Ens', feat: 'Prop', fullScaleView: 'Visus plenae scalae', 
        uploadedImage: 'Imago imposita', preview: 'Praevisus', uploadImage: 'Imaginem imponere',
        errCorruptedFile: 'Fasciculus electus legi non potuit. Fortasse corruptus est aut non est fasciculus clavis Lucid validus (zip, lk4, lk5).', errDataDirNotFound: 'Zip clavis Lucid invalidum: directorium "Data" non inventum.', errKeyDataNotFound: 'Non potuit inveniri vel legi "key.data" ex archivo nidificato.', errProcessingKey: 'Fasciculus clavis tractari non potuit.',
        prefsGeneral: 'Generalia', prefsAI: 'Configuratio AI',
    },
    'it': {
        openNativeKey: 'Apri Chiave', importKey: 'Importa Chiave', clearFeatures: 'Cancella Caratteristiche', preferences: 'Preferenze', assistant: 'Spot',
        loadKeyPrompt: 'Carica una chiave Lucid per iniziare.', processing: 'In elaborazione...', error: 'Errore', canceled: 'Annullato',
        toggleMenu: 'Attiva/disattiva menu', features: 'Caratteristiche', entitiesRemaining: 'Entità Rimanenti',
        featuresChosen: 'Caratteristiche Scelte', entitiesDiscarded: 'Entità Scartate', search: 'Cerca...',
        listView: 'Visualizzazione elenco', gridView: 'Visualizzazione griglia', clearHistory: 'Cancella cronologia', closePanel: 'Chiudi pannello',
        folder: 'Cartella',
        noImageAvailable: 'Nessuna immagine disponibile', keyInfo: 'Informazioni sulla Chiave', language: 'Lingua',
        uiTheme: 'Tema Interfaccia', themeLight: 'Chiaro', themeDark: 'Scuro',
        uiShowToasts: 'Mostra Notifiche',
        confirmClear: 'Sei sicuro di voler cancellare tutte le caratteristiche scelte?', featuresCleared: 'Tutte le caratteristiche cancellate.',
        aiReady: 'Descrivi un\'entità per identificarla, oppure fai una domanda su questa chiave.',
        aiWaiting: 'In attesa...', aiDescribe: 'Chiedi a Spot...', aiNeedApi: 'Aggiungi la tua chiave API nelle preferenze.',
        aiNeedKey: 'Carica prima una chiave.', aiAnalyzing: 'Analisi in corso...',
        aiNoFeatures: "Non sono riuscito a identificare alcuna caratteristica specifica dalla tua descrizione. Potresti fornire maggiori dettagli?",
        aiSingleMatch: 'In base alla tua descrizione, l\'unica corrispondenza possibile è',
        aiMultipleMatches: 'In base alla tua descrizione, ci sono **{count}** corrispondenze possibili:',
        aiNoMatch: 'Ho trovato delle caratteristiche nella tua descrizione, ma nessuna entità corrisponde a tutte.',
        aiError: 'Spiacenti, si è verificato un errore', otherFeature: 'Altro', value: 'Valore',
        scoreCommon: 'Comune', scoreRare: 'Raro', scoreUncertain: 'Incerto', scoreInterval: 'Intervallo',
        enterApiKey: 'Inserisci la tua chiave API...',
        apiKeyNote: 'La tua chiave API è memorizzata solo nel tuo browser ed è richiesta per l\'assistente AI.',
        scoreCommonMisinterpret: 'Comune (mal interpretato)',
        hierarchy: 'Gerarchia',
        back: 'Indietro',
        scoreRareMisinterpret: 'Raro (mal interpretato)',
        charParentOther: 'Altri',
        aiFeaturesConsidered: 'Caratteristiche Considerate:',
        aiEntitiesConsidered: 'Entità Considerate:',
        aiConsideredData: 'Dati Considerati',
        aiDisclaimer: 'Le risposte dell\'IA potrebbero contenere informazioni errate. Si prega di verificare i dettagli importanti.',
        featureUpdated: 'Caratteristica aggiornata.',
        entitiesDiscardedCount: '{count} entità scartate. {remain} rimanenti.',
        entitiesRestoredCount: '{count} entità ripristinate. {remain} rimanenti.',
        confirmClearHistory: 'Sei sicuro di voler cancellare la cronologia della chat?',
        copy: 'Copia',
        copied: 'Copiato!',
        readMore: 'Leggi di più',
        readLess: 'Mostra meno',
        regenerate: 'Rigenera',
        edit: 'Modifica',
        cancel: 'Annulla',
        save: 'Salva',
        expandAll: 'Espandi tutto',
        collapseAll: 'Comprimi tutto',
        clearSearch: 'Cancella ricerca', prevMatch: 'Corrispondenza precedente', nextMatch: 'Corrispondenza successiva', loading: 'Caricamento...', 
        dropImageHere: 'Rilascia l\'immagine qui', previousVersion: 'Versione precedente', nextVersion: 'Versione successiva', 
        resizePanel: 'Ridimensiona pannello', ent: 'Ent', feat: 'Carat', fullScaleView: 'Visualizzazione a grandezza naturale', 
        uploadedImage: 'Immagine caricata', preview: 'Anteprima', uploadImage: 'Carica Immagine',
        errCorruptedFile: 'Impossibile leggere il file selezionato. Potrebbe essere danneggiato o non essere un file di chiave Lucid valido (zip, lk4, lk5).', errDataDirNotFound: 'Zip della chiave Lucid non valido: directory "Data" non trovata.', errKeyDataNotFound: 'Impossibile trovare o leggere "key.data" dall\'archivio nidificato.', errProcessingKey: 'Impossibile elaborare il file della chiave.',
        prefsGeneral: 'Generale', prefsAI: 'Configurazione IA',
    }
};
